INSERT INTO `cs_type_config` VALUES ('1', '业务问题', '1')
INSERT INTO `cs_type_config` VALUES ('2', '操作问题', '2')
INSERT INTO `cs_type_config` VALUES ('3', '其他问题', '3')

INSERT INTO `cs_system_config` VALUES ('1', '沃易售', '1', 'woyishou.png')
INSERT INTO `cs_system_config` VALUES ('2', '沃运营', '2', 'woyunying.png')
INSERT INTO `cs_system_config` VALUES ('3', '数字化app', '3', 'shuzihua.png')
INSERT INTO `cs_system_config` VALUES ('4', '移动门户', '4', 'yidongmenhu.png')

INSERT INTO `cs_customer_config` VALUES ('1', '沃易售', '业务问题', '')
INSERT INTO `cs_customer_config` VALUES ('2', '沃易售', '操作问题', '')
INSERT INTO `cs_customer_config` VALUES ('3', '沃易售', '其他问题', '')
INSERT INTO `cs_customer_config` VALUES ('4', '沃运营', '业务问题', '')
INSERT INTO `cs_customer_config` VALUES ('5', '沃运营', '操作问题', '')
INSERT INTO `cs_customer_config` VALUES ('6', '沃运营', '其他问题', '')
INSERT INTO `cs_customer_config` VALUES ('7', '数字化app', '业务问题', '')
INSERT INTO `cs_customer_config` VALUES ('8', '数字化app', '操作问题', '')
INSERT INTO `cs_customer_config` VALUES ('9', '数字化app', '其他问题', '')
INSERT INTO `cs_customer_config` VALUES ('10', '移动门户', '业务问题', null)
INSERT INTO `cs_customer_config` VALUES ('11', '移动门户', '操作问题', null)
INSERT INTO `cs_customer_config` VALUES ('12', '移动门户', '其他问题', '')

INSERT INTO `cs_cusaccount_config` VALUES ('1', 'zhouxx16', '周曦旭', '1')
INSERT INTO `cs_cusaccount_config` VALUES ('2', 'bjsc-xinghr1', '刑海荣', '1')
INSERT INTO `cs_cusaccount_config` VALUES ('3', 'zhouxy6', '周小寅', '1')
INSERT INTO `cs_cusaccount_config` VALUES ('4', 'zhouquan5', '周全', '2')
INSERT INTO `cs_cusaccount_config` VALUES ('5', 'bjsc-xingjian1', '刑健', '2')
INSERT INTO `cs_cusaccount_config` VALUES ('6', 'zhout10 ', '周涛', '2')
INSERT INTO `cs_cusaccount_config` VALUES ('7', 'zhourong2', '周荣', '3')
INSERT INTO `cs_cusaccount_config` VALUES ('8', 'tianmei1', '田梅', '3')
INSERT INTO `cs_cusaccount_config` VALUES ('9', 'zhourui2', '周锐', '3')
INSERT INTO `cs_cusaccount_config` VALUES ('10', 'zhouxx16', '周曦旭', '4')
INSERT INTO `cs_cusaccount_config` VALUES ('11', 'bjsc-xinghr1', '刑海荣', '4')
INSERT INTO `cs_cusaccount_config` VALUES ('12', 'zhouxy6', '周小寅', '4')
INSERT INTO `cs_cusaccount_config` VALUES ('13', 'zhouquan5', '周全', '5')
INSERT INTO `cs_cusaccount_config` VALUES ('14', 'bjsc-xingjian1', '刑健', '5')
INSERT INTO `cs_cusaccount_config` VALUES ('15', 'zhout10 ', '周涛', '5')
INSERT INTO `cs_cusaccount_config` VALUES ('16', 'zhourong2', '周荣', '6')
INSERT INTO `cs_cusaccount_config` VALUES ('17', 'tianmei1', '田梅', '6')
INSERT INTO `cs_cusaccount_config` VALUES ('18', 'zhourui2', '周锐', '6')
INSERT INTO `cs_cusaccount_config` VALUES ('19', 'tianmei1', '田梅', '7')
INSERT INTO `cs_cusaccount_config` VALUES ('20', 'zhouruimin', '周瑞民', '7')
INSERT INTO `cs_cusaccount_config` VALUES ('21', 'zhouwei30', '周蔚', '7')
INSERT INTO `cs_cusaccount_config` VALUES ('22', 'tianmei1', '田梅', '8')
INSERT INTO `cs_cusaccount_config` VALUES ('23', 'zhouruimin', '周瑞民', '8')
INSERT INTO `cs_cusaccount_config` VALUES ('24', 'zhouwei30', '周蔚', '8')
INSERT INTO `cs_cusaccount_config` VALUES ('25', 'tianmei1', '田梅', '9')
INSERT INTO `cs_cusaccount_config` VALUES ('26', 'zhouruimin', '周瑞民', '9')
INSERT INTO `cs_cusaccount_config` VALUES ('27', 'zhouwei30', '周蔚', '9')
INSERT INTO `cs_cusaccount_config` VALUES ('28', 'bjsc-liangam1', '梁爱明', '10')
INSERT INTO `cs_cusaccount_config` VALUES ('29', 'bjsc-liangam1', '梁爱明', '11')
INSERT INTO `cs_cusaccount_config` VALUES ('30', 'bjsc-liangam1', '梁爱明', '12')